=== vukovic98/xml_veb_servisi/xml/data/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://www.ftn.uns.ac.rs/zahtev" xmlns="http://www.ftn.uns.ac.rs/zahtev">
  <xs:element name="zahtev">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="podaci_o_organu"/>
        <xs:element ref="sadrzaj_zahteva"/>
        <xs:element ref="podnozje"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="podaci_o_organu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="naziv"/>
        <xs:element ref="sediste"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naziv" type="xs:string"> </xs:element>
  <xs:element name="sediste" type="xs:string"> </xs:element>
  <xs:element name="sadrzaj_zahteva">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="naslov"/>
        <xs:element ref="paragraf"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naslov" type="xs:string"/>
  <xs:element name="paragraf">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="opis_trazene_informacije"/>
        <xs:element ref="sluzbeni_glasnik"/>
        <xs:element ref="stavke"/>
        <xs:element ref="zakon"/>
      </xs:choice>
      <xs:attribute name="fusnota" use="optional"/>
      <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="opis_trazene_informacije" type="xs:string">
  </xs:element>
  <xs:element name="sluzbeni_glasnik">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="brojevi"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="brojevi">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="broj"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="broj" type="xs:string"></xs:element>
  <xs:element name="stavke">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="stavka"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="stavka">
    <xs:complexType>
      <xs:sequence minOccurs="0">
        <xs:element minOccurs="0" ref="podstavke"/>
      </xs:sequence>
      <xs:attribute name="fusnota" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="otkaceno" use="optional" type="xs:boolean" default="false"/>
      <xs:attribute name="zahtev" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="podstavke">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="podstavka"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="podstavka">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="drugi_nacin"/>
      </xs:sequence>
      <xs:attribute name="fusnota" use="optional" type="xs:string"/>
      <xs:attribute name="id" use="required" type="xs:ID"/>
      <xs:attribute name="nacin" use="required" type="xs:string"/>
      <xs:attribute name="otkaceno" use="optional" type="xs:boolean" default="false"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="drugi_nacin" type="xs:string"> </xs:element>
  <xs:element name="zakon">
    <xs:complexType>
      <xs:attribute name="naziv" use="required" type="xs:string"/>
      <xs:attribute name="stav" use="required" type="xs:integer"/>
      <xs:attribute name="clan" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="podnozje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mesto_i_datum"/>
        <xs:element ref="informacije_o_traziocu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mesto_i_datum">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mesto"/>
        <xs:element ref="datum"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="datum" type="xs:date"> </xs:element>
  <xs:element name="informacije_o_traziocu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ime_i_prezime"/>
        <xs:element ref="adresa"/>
        <xs:element ref="kontakt"/>
        <xs:element ref="potpis"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ime_i_prezime" type="xs:string"> </xs:element>
  <xs:element name="adresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ulica"/>
        <xs:element ref="brojUlice"/>
        <xs:element ref="mesto"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ulica" type="xs:string"> </xs:element>
  <xs:element name="kontakt" type="xs:string"> </xs:element>
  <xs:element name="potpis" type="xs:string"> </xs:element>
  <xs:element name="brojUlice" type="xs:positiveInteger"> </xs:element>
  <xs:element name="mesto" type="xs:string"> </xs:element>
</xs:schema>

=== vukovic98/xml_veb_servisi/xml/data/zahtev.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev
    xmlns="http://www.ftn.uns.ac.rs/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev zahtev.xsd">
    <podaci_o_organu>
        <naziv></naziv>
        <sediste></sediste>
    </podaci_o_organu>
    <sadrzaj_zahteva>
        <naslov>
                        З А Х Т Е В
            за приступ информацији од јавног значаја
        </naslov>
        <paragraf id="p_1" fusnota="У кућици означити која законска права на приступ информацијама желите да остварите">
            На основу <zakon naziv="Закон о слободном приступу информацијама од јавног значаја" clan="15" stav="1"></zakon>
           (<sluzbeni_glasnik>
                <brojevi>
                    <broj br="120/04"></broj>
                    <broj br="57/04"></broj>
                    <broj br="104/09"></broj>
                    <broj br="36/10"></broj>
                </brojevi>
            </sluzbeni_glasnik>), од горе наведеног органа захтевам:
            <stavke>
                <stavka otkaceno = "false" id="s_1" zahtev="обавештење да ли поседује тражену информацију" ></stavka>;
                <stavka otkaceno = "false" id="s_2" zahtev="увид у документ који садржи тражену информацију" ></stavka>;
                <stavka otkaceno = "false" id="s_3" zahtev="копију документа који садржи тражену информацију" ></stavka>;
                <stavka otkaceno = "false" id="s_4" zahtev="достављање копије документа који садржи тражену информацију:" fusnota="У кућици означити начин достављања копије докумената.">
                    <podstavke>
                        <podstavka otkaceno = "false" id="ps_1" nacin="поштом" fusnota=""></podstavka>
                        <podstavka otkaceno = "false" id="ps_2" nacin="електронском поштом" fusnota=""></podstavka>
                        <podstavka otkaceno = "false" id="ps_3" nacin="факсом" fusnota=""></podstavka>
                        <podstavka otkaceno = "false" id="ps_4" nacin="на други начин:" fusnota="Када захтевате други начин достављања обавезно уписати који начин достављања захтевате.">
                            <drugi_nacin> </drugi_nacin>
                        </podstavka>
                    </podstavke>
                </stavka>
            </stavke>
            Овај захтев се односи на следеће информације:
            <opis_trazene_informacije></opis_trazene_informacije>
        </paragraf>
    </sadrzaj_zahteva>
    <podnozje>
        <mesto_i_datum>
            <mesto></mesto>
            <datum>2020-12-04</datum> 
        </mesto_i_datum>
        <informacije_o_traziocu>
            <ime_i_prezime> </ime_i_prezime>
            <adresa> 
                <ulica></ulica>
                <broj></broj>
                <mesto></mesto>
            </adresa>
            <kontakt> </kontakt>
            <potpis> </potpis>
        </informacije_o_traziocu>
    </podnozje>
</zahtev>

=== vukovic98/xml_veb_servisi/xml/bin/data/zahtev.xml
<?xml version="1.0" encoding="UTF-8"?>
<zahtev
    xmlns="http://www.ftn.uns.ac.rs/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev zahtev.xsd">
    <podaci_o_organu>
        <naziv></naziv>
        <sedište></sedište>
    </podaci_o_organu>
    <sadržaj_zahteva>
        <naslov>
                        З А Х Т Е В
            за приступ информацији од јавног значаја
        </naslov>
        <paragraf id="p_1" fusnota="У кућици означити која законска права на приступ информацијама желите да остварите">
            На основу <zakon naziv="Закон о слободном приступу информацијама од јавног значаја" član="15" stav="1"></zakon>
           (<službeni_glasnik>
                <brojevi>
                    <broj br="120/04"></broj>
                    <broj br="57/04"></broj>
                    <broj br="104/09"></broj>
                    <broj br="36/10"></broj>
                </brojevi>
            </službeni_glasnik>), од горе наведеног органа захтевам:
            <stavke>
                <stavka otkačeno = "false" id="s_1" zahtev="обавештење да ли поседује тражену информацију" ></stavka>;
                <stavka otkačeno = "false" id="s_2" zahtev="увид у документ који садржи тражену информацију" ></stavka>;
                <stavka otkačeno = "false" id="s_3" zahtev="копију документа који садржи тражену информацију" ></stavka>;
                <stavka otkačeno = "false" id="s_4" zahtev="достављање копије документа који садржи тражену информацију:" fusnota="У кућици означити начин достављања копије докумената.">
                    <podstavke>
                        <podstavka otkačeno = "false" id="ps_1" način="поштом" fusnota=""></podstavka>
                        <podstavka otkačeno = "false" id="ps_2" način="електронском поштом" fusnota=""></podstavka>
                        <podstavka otkačeno = "false" id="ps_3" način="факсом" fusnota=""></podstavka>
                        <podstavka otkačeno = "false" id="ps_4" način="на други начин:" fusnota="Када захтевате други начин достављања обавезно уписати који начин достављања захтевате.">
                            <drugi_način> </drugi_način>
                        </podstavka>
                    </podstavke>
                </stavka>
            </stavke>
            Овај захтев се односи на следеће информације:
            <opis_tražene_informacije></opis_tražene_informacije>
        </paragraf>
    </sadržaj_zahteva>
    <podnožje>
        <mesto_i_datum>
            <mesto></mesto>
            <datum>2020-12-04</datum> 
        </mesto_i_datum>
        <informacije_o_tražiocu>
            <ime_i_prezime> </ime_i_prezime>
            <adresa> 
                <ulica></ulica>
                <broj></broj>
                <mesto></mesto>
            </adresa>
            <kontakt> </kontakt>
            <potpis> </potpis>
        </informacije_o_tražiocu>
    </podnožje>
</zahtev>
