=== vukovic98/xml_veb_servisi/apps/sluzbenik_be/data/korisnik.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://ftn.uns.ac.rs/korisnik" xmlns:korisnik="http://ftn.uns.ac.rs/korisnik"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="lista_korisnika">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="korisnik:korisnik"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="korisnik">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="korisnik:ime_i_prezime"/>
        <xs:element ref="korisnik:email"/>
        <xs:element ref="korisnik:lozinka"/>
        <xs:element ref="korisnik:uloga"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ime_i_prezime" type="xs:string"/>
  <xs:element name="email" type="xs:string"/>
  <xs:element name="lozinka" type="xs:string"/>
  <xs:element name="uloga" type="xs:string"/>
</xs:schema>

=== vukovic98/xml_veb_servisi/apps/sluzbenik_be/data/korisnik.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_korisnika 
    xmlns="http://ftn.uns.ac.rs/korisnik"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ftn.uns.ac.rs/korisnik korisnik.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#">
    
    <korisnik>
        <ime_i_prezime>Sluzbenik Sluzbenik</ime_i_prezime>
        <email>sluzbenik@maildrop.cc</email>
        <lozinka>sluzbenik</lozinka>
        <uloga>S</uloga>
    </korisnik>
    
    <korisnik>
        <ime_i_prezime>Vladimir Vukovic</ime_i_prezime>
        <email>vladimirvukovic98@maildrop.cc</email>
        <lozinka>vukovic</lozinka>
        <uloga>K</uloga>
    </korisnik>
    
    <korisnik>
        <ime_i_prezime>Ivana Vlaisavljevic</ime_i_prezime>
        <email>ivanazvucnik@maildrop.cc</email>
        <lozinka>zvucnik</lozinka>
        <uloga>K</uloga>
    </korisnik>
</lista_korisnika>
