=== vukovic98/xml_veb_servisi/apps/sluzbenik_be/data/obavestenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://ftn.uns.ac.rs/obavestenje" xmlns:o="http://ftn.uns.ac.rs/obavestenje"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="lista_obavestenja">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="o:obavestenje"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="obavestenje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="o:osnovni_podaci"/>
        <xs:element ref="o:sadrzaj"/>
        <xs:element ref="o:podnozje"/>
        <xs:element ref="o:broj_zahteva"/>
      </xs:sequence>
      <xs:attribute name="about" use="required" type="xs:anyURI"/>
      <xs:attribute name="vocab" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="osnovni_podaci">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="o:podaci_o_organu"/>
        <xs:element ref="o:podaci_o_podnosiocu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="podaci_o_organu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="o:naziv"/>
        <xs:element ref="o:sediste"/>
        <xs:element ref="o:broj_predmeta"/>
        <xs:element ref="o:datum_zahteva"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naziv">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sediste">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="broj_predmeta">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="datum_zahteva">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:date">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="podaci_o_podnosiocu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="o:ime_i_prezime"/>
        <xs:element ref="o:naziv_podnosioca"/>
        <xs:element ref="o:adresa_podnosioca"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ime_i_prezime">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="naziv_podnosioca">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="adresa_podnosioca">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sadrzaj">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="o:godina_zahteva"/>
        <xs:element ref="o:opis_trazene_informacije"/>
        <xs:element ref="o:datum_uvida"/>
        <xs:element ref="o:cas_uvida"/>
        <xs:element ref="o:sat_od"/>
        <xs:element ref="o:sat_do"/>
        <xs:element ref="o:adresa"/>
        <xs:element ref="o:broj_kancelarije"/>
        <xs:element ref="o:cena"/>
        <xs:element ref="o:ziro_racun"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="godina_zahteva">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="opis_trazene_informacije">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datum_uvida" type="xs:string"/>
  <xs:element name="cas_uvida" type="xs:string"/>
  <xs:element name="sat_od" type="xs:string"/>
  <xs:element name="sat_do" type="xs:string"/>
  <xs:element name="adresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="o:grad"/>
        <xs:element ref="o:ulica"/>
        <xs:element ref="o:broj"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="grad" type="xs:string"/>
  <xs:element name="ulica" type="xs:string"/>
  <xs:element name="broj" type="xs:integer"/>
  <xs:element name="broj_kancelarije" type="xs:integer"/>
  <xs:element name="cena" type="xs:decimal"/>
  <xs:element name="ziro_racun">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NMTOKEN">
          <xs:attribute name="poziv_na_broj" use="required" type="xs:integer"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="podnozje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="o:potpis_ovlascenog_lica"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="potpis_ovlascenog_lica">
    <xs:complexType/>
  </xs:element>
  <xs:element name="broj_zahteva">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vukovic98/xml_veb_servisi/apps/poverenik_be/bin/data/obavestenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_obavestenja
	xmlns="http://www.w3.org/ns/obavestenje" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ftn.uns.ac.rs/obavestenje obavestenje.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:obav="http://www.ftn.uns.ac.rs/rdf/example"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/"
    >
    <obavestenje about="http://www.ftn.uns.ac.rs/rdf/examples/obavestenje/1" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
        <osnovni_podaci>
            <podaci_o_organu>
                <naziv datatype="xs:string" property="pred:naziv_ustanove">FTN</naziv>
                <sediste datatype="xs:string" property="pred:sediste_ustanove">Novi Sad</sediste>
                <broj_predmeta datatype="xs:string" property="pred:br_predmeta">12345</broj_predmeta>
                <datum_zahteva datatype="xs:string" property="pred:datum_zahteva">2020-12-24</datum_zahteva>
            </podaci_o_organu>
            <podaci_o_podnosiocu>
                <ime_i_prezime datatype="xs:string" property="pred:ime_podnosioca">Vladimir Vukovic</ime_i_prezime>
                <naziv datatype="xs:string" property="pred:naziv_podnosioca">Raska</naziv>
                <adresa datatype="xs:string" property="pred:adresa_podnosioca">Tomice Aleksic 25</adresa>
            </podaci_o_podnosiocu>
        </osnovni_podaci>
        <sadrzaj>
            <godina_zahteva datatype="xs:integer" property="pred:godina_zahteva">2020</godina_zahteva>
            <opis_trazene_informacije datatype="xs:string" property="pred:opis">Uvid u spisak polozenih ispita</opis_trazene_informacije>
            <datum_uvida>2020-12-04</datum_uvida>
            <cas_uvida>15:30:00</cas_uvida>
            <sat_od>14:26:30</sat_od>
            <sat_do>20:26:00</sat_do>
            <adresa>
                <grad>Novi Sad</grad>
                <ulica>Adresa fakulteta</ulica>
                <broj>23</broj>
            </adresa>
            <broj_kancelarije>12</broj_kancelarije>
            <cena>176.00</cena>
            <ziro_racun poziv_na_broj="97">840-74232884311-30</ziro_racun>
        </sadrzaj>
        <podnozje>
            <potpis_ovlascenog_lica/>
        </podnozje>
        <broj_zahteva datatype="xs:string" property="pred:broj_zahteva">1</broj_zahteva>
    </obavestenje>
    
    <obavestenje about="http://www.ftn.uns.ac.rs/rdf/examples/obavestenje/2" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
        <osnovni_podaci>
            <podaci_o_organu>
                <naziv datatype="xs:string" property="pred:naziv_ustanove">FTN</naziv>
                <sediste datatype="xs:string" property="pred:sediste_ustanove">Novi Sad</sediste>
                <broj_predmeta datatype="xs:string" property="pred:br_predmeta">1234567</broj_predmeta>
                <datum_zahteva datatype="xs:string" property="pred:datum_zahteva">2020-12-24</datum_zahteva>
            </podaci_o_organu>
            <podaci_o_podnosiocu>
                <ime_i_prezime datatype="xs:string" property="pred:ime_podnosioca">Vladimir Vukovic</ime_i_prezime>
                <naziv datatype="xs:string" property="pred:naziv_podnosioca">Raska</naziv>
                <adresa datatype="xs:string" property="pred:adresa_podnosioca">Tomice Aleksic 25</adresa>
            </podaci_o_podnosiocu>
        </osnovni_podaci>
        <sadrzaj>
            <godina_zahteva datatype="xs:integer" property="pred:godina_zahteva">2020</godina_zahteva>
            <opis_trazene_informacije datatype="xs:string" property="pred:opis">Uvid u spisak polozenih ispita</opis_trazene_informacije>
            <datum_uvida>2020-12-04</datum_uvida>
            <cas_uvida>15:30:00</cas_uvida>
            <sat_od>14:26:30</sat_od>
            <sat_do>20:26:00</sat_do>
            <adresa>
                <grad>Novi Sad</grad>
                <ulica>Adresa fakulteta</ulica>
                <broj>23</broj>
            </adresa>
            <broj_kancelarije>12</broj_kancelarije>
            <cena>176.00</cena>
            <ziro_racun poziv_na_broj="97">840-74232884311-30</ziro_racun>
        </sadrzaj>
        <podnozje>
            <potpis_ovlascenog_lica/>
        </podnozje>
        <broj_zahteva datatype="xs:string" property="pred:broj_zahteva">2</broj_zahteva>
    </obavestenje>

</lista_obavestenja>
