=== vukovic98/xml_veb_servisi/apps/poverenik_be/data/zalba_na_odluku.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://ftn.uns.ac.rs/zalba_na_odluku"
  xmlns:z="http://ftn.uns.ac.rs/zalba_na_odluku"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="lista_zalbi_na_odluku">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="z:zalba_na_odluku"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="zalba_na_odluku">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="z:osnovni_podaci"/>
        <xs:element ref="z:sadrzaj"/>
        <xs:element ref="z:podnozje"/>
        <xs:element ref="z:broj_zahteva"/>
      </xs:sequence>
      <xs:attribute name="about" use="required" type="xs:anyURI"/>
      <xs:attribute name="vocab" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="osnovni_podaci">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="z:podaci_o_zaliocu"/>
        <xs:element ref="z:podaci_o_organu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="podaci_o_organu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="z:naziv"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naziv">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="sadrzaj">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="z:broj_zalbe"/>
        <xs:element ref="z:godina_zalbe"/>
        <xs:element ref="z:datum_odbijenog_zahteva"/>
        <xs:element ref="z:odluka_organa_vlasti"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="broj_zalbe">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="godina_zalbe">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="datum_odbijenog_zahteva">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="odluka_organa_vlasti">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="podnozje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="z:mesto_zakljucka_zalbe"/>
        <xs:element ref="z:datum_zakljucka_zalbe"/>
        <xs:element ref="z:podaci_o_zaliocu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mesto_zakljucka_zalbe">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datum_zakljucka_zalbe">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="broj_zahteva">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="podaci_o_zaliocu">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="z:korisnik_email"/>
        <xs:element ref="z:zalioc_ime"/>
        <xs:element ref="z:zalioc_prezime"/>
        <xs:element minOccurs="0" ref="z:zalioc_naziv_zalbe"/>
        <xs:element ref="z:zalioc_adresa"/>
        <xs:choice>
          <xs:element ref="z:zalioc_sediste"/>
          <xs:sequence>
            <xs:element ref="z:drugi_podaci_za_kontakt"/>
            <xs:element ref="z:potpis_zalioca"/>
          </xs:sequence>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="korisnik_email">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="zalioc_ime">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="zalioc_prezime">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="zalioc_naziv_zalbe">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="zalioc_adresa">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="zalioc_sediste">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="drugi_podaci_za_kontakt">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="potpis_zalioca">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vukovic98/xml_veb_servisi/xml/data/zalba_na_odluku.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_zalbi_na_odluku
    xmlns="http://ftn.uns.ac.rs/zalba_na_odluku"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ftn.uns.ac.rs/zalba_na_odluku zalba_na_odluku.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:obav="http://www.ftn.uns.ac.rs/rdf/example"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/"
    >
    <zalba_na_odluku vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/" 
    			about="http://www.ftn.uns.ac.rs/rdf/examples/resenje/101">
    <osnovni_podaci>            
    	<podaci_o_zaliocu>
    		<zalioc_ime property="pred:ime_zalioca" datatype="xs:string">Nikola</zalioc_ime>
    		<zalioc_prezime property="pred:prezime_zalioca" datatype="xs:string">Petrovic</zalioc_prezime>
    		<zalioc_naziv_zalbe property="pred:naziv_zalbe" datatype="xs:string">Zalba1</zalioc_naziv_zalbe>
    		<zalioc_adresa property="pred:adresa_zalioca" datatype="xs:string">Mise Dimitrijevica 44</zalioc_adresa>
    		<zalioc_sediste property="pred:sediste_zalioca" datatype="xs:string">Novi Sad</zalioc_sediste>
       
		</podaci_o_zaliocu>
        
        <podaci_o_organu>
        	<naziv property="pred:naziv_organa" datatype="xs:string">FTN</naziv>
        </podaci_o_organu>

	</osnovni_podaci>   
    
   <sadrzaj>
   		<broj_zalbe property="pred:broj_zalbe" datatype="xs:integer">101</broj_zalbe>
   		<godina_zalbe property="pred:godina_zalbe" datatype="xs:string">2020</godina_zalbe>
   		<datum_odbijenog_zahteva property="pred:datum_odbijenog_zahteva" datatype="xs:string">2020-12-04</datum_odbijenog_zahteva>
   		<odluka_organa_vlasti property="pred:odluka" datatype="xs:string">Odluka organa vlasti</odluka_organa_vlasti>
   </sadrzaj>
   
   <podnozje>
   		<mesto_zakljucka_zalbe property="pred:mesto_zakljucka_zalbe" datatype="xs:string">Novi Sad</mesto_zakljucka_zalbe>
   		<datum_zakljucka_zalbe property="pred:datum_zakljucka_zalbe" datatype="xs:string">2021-01-12</datum_zakljucka_zalbe>
   		
   		<podaci_o_zaliocu>
    		<zalioc_ime property="pred:ime_zalioca" datatype="xs:string">Nikola</zalioc_ime>
    		<zalioc_prezime property="pred:prezime_zalioca" datatype="xs:string">Petrovic</zalioc_prezime>
    		<zalioc_adresa property="pred:adresa_zalioca" datatype="xs:string">Mise Dimitrijevica 44</zalioc_adresa>
    		<drugi_podaci_za_kontakt property="pred:kontakt_zalioca" datatype="xs:string">petrovicnik96@gmail.com</drugi_podaci_za_kontakt>
    		<potpis_zalioca property="pred:potpis_zalioca" datatype="xs:string">NikolaPetrovic</potpis_zalioca>
    		
		</podaci_o_zaliocu>
   </podnozje>
           
     </zalba_na_odluku>
</lista_zalbi_na_odluku>

=== vukovic98/xml_veb_servisi/apps/poverenik_be/data/zalba_na_odluku.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_zalbi_na_odluku xmlns="http://ftn.uns.ac.rs/zalba_na_odluku"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ftn.uns.ac.rs/zalba_na_odluku zalba_na_odluku.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:obav="http://www.ftn.uns.ac.rs/rdf/example"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
    
<zalba_na_odluku about="http://www.ftn.uns.ac.rs/rdf/examples/zalba_na_odluku/1" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
    <osnovni_podaci>
        <podaci_o_zaliocu>
            <korisnik_email datatype="xs:string" property="pred:korisnik">vladimirvukovic98@maildrop.cc</korisnik_email>
            <zalioc_ime datatype="xs:string" property="pred:ime_zalioca">Vladimir</zalioc_ime>
            <zalioc_prezime datatype="xs:string" property="pred:prezime_zalioca">Vukovic</zalioc_prezime>
            <zalioc_naziv_zalbe datatype="xs:string" property="pred:naziv_zalbe">Zalba 1</zalioc_naziv_zalbe>
            <zalioc_adresa datatype="xs:string" property="pred:adresa_zalioca">Mise Dimitrijevica 44</zalioc_adresa>
            <zalioc_sediste datatype="xs:string" property="pred:sediste_zalioca">Novi Sad</zalioc_sediste>
        </podaci_o_zaliocu>
        <podaci_o_organu>
            <naziv datatype="xs:string" property="pred:naziv_organa">FT N</naziv>
        </podaci_o_organu>
    </osnovni_podaci>
    <sadrzaj>
        <broj_zalbe datatype="xs:integer" property="pred:broj_zalbe">101</broj_zalbe>
        <godina_zalbe datatype="xs:string" property="pred:godina_zalbe">2020</godina_zalbe>
        <datum_odbijenog_zahteva datatype="xs:string" property="pred:datum_odbijenog_zahteva">2020-12-04</datum_odbijenog_zahteva>
        <odluka_organa_vlasti datatype="xs:string" property="pred:odluka">Odluka organa vlasti</odluka_organa_vlasti>
    </sadrzaj>
    <podnozje>
        <mesto_zakljucka_zalbe datatype="xs:string" property="pred:mesto_zakljucka_zalbe">Novi Sad</mesto_zakljucka_zalbe>
        <datum_zakljucka_zalbe datatype="xs:string" property="pred:datum_zakljucka_zalbe">2021-01-12</datum_zakljucka_zalbe>
        <podaci_o_zaliocu>
            <zalioc_ime datatype="xs:string" property="pred:ime_zalioca">Nikola</zalioc_ime>
            <zalioc_prezime datatype="xs:string" property="pred:prezime_zalioca">Petrovic</zalioc_prezime>
            <zalioc_adresa datatype="xs:string" property="pred:adresa_zalioca">Mise Dimitrijevica 44</zalioc_adresa>
            <drugi_podaci_za_kontakt datatype="xs:string" property="pred:kontakt_zalioca">petrovicnik96@gmail.com</drugi_podaci_za_kontakt>
            <potpis_zalioca datatype="xs:string" property="pred:potpis_zalioca"></potpis_zalioca>
        </podaci_o_zaliocu>
    </podnozje>
    <broj_zahteva datatype="xs:string" property="pred:broj_zahteva">3</broj_zahteva>
</zalba_na_odluku>
</lista_zalbi_na_odluku>
