=== vukovic98/xml_veb_servisi/apps/sluzbenik_be/src/main/resources/static/xsd/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://www.ftn.uns.ac.rs/zahtev"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:zahtev="http://www.ftn.uns.ac.rs/zahtev">
  <xs:element name="lista_zahteva_za_pristup_informacijama">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="zahtev:zahtev_za_pristup_informacijama"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="zahtev_za_pristup_informacijama">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zahtev:podaci_o_organu"/>
        <xs:element ref="zahtev:sadrzaj"/>
        <xs:element ref="zahtev:podnozje"/>
        <xs:element ref="zahtev:status"></xs:element>
      </xs:sequence>
      <xs:attribute name="about" use="required" type="xs:anyURI"/>
      <xs:attribute name="vocab" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="podaci_o_organu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zahtev:naziv"/>
        <xs:element ref="zahtev:sediste"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naziv">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sediste">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sadrzaj">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zahtev:zahtevi"/>
        <xs:element ref="zahtev:opis_trazene_informacije"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="zahtevi">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="zahtev:zahtev"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="zahtev">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="zahtev:nacini_dostave"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="opis_zahteva" use="required" type="xs:string"/>
      <xs:attribute name="otkaceno" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="nacini_dostave">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="zahtev:nacin"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nacin">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="zahtev:drugi_nacin"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="opis_nacina" use="required" type="xs:string"/>
      <xs:attribute name="otkaceno" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="drugi_nacin" type="xs:string"/>
  <xs:element name="opis_trazene_informacije">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="podnozje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zahtev:mesto_i_datum"/>
        <xs:element ref="zahtev:informacije_o_traziocu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="mesto_i_datum">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zahtev:mesto"/>
        <xs:element ref="zahtev:datum_zahteva"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="datum_zahteva">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:date">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="informacije_o_traziocu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zahtev:korisnik_email"/>
        <xs:element ref="zahtev:ime_i_prezime"/>
        <xs:element ref="zahtev:adresa"/>
        <xs:element ref="zahtev:kontakt"/>
        <xs:element ref="zahtev:potpis"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="korisnik_email">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ime_i_prezime">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="adresa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zahtev:ulica"/>
        <xs:element ref="zahtev:broj"/>
        <xs:element ref="zahtev:mesto"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ulica">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="broj">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="kontakt">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="potpis">
    <xs:complexType/>
  </xs:element>
  <xs:element name="mesto">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" type="xs:NMTOKEN"/>
      <xs:attribute name="property" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="status" type="xs:string"/>
</xs:schema>

=== vukovic98/xml_veb_servisi/apps/poverenik_be/bin/data/zahtev.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_zahteva_za_pristup_informacijama 
    xmlns="http://www.ftn.uns.ac.rs/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.ftn.uns.ac.rs/zahtev zahtev.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:z="http://www.ftn.uns.ac.rs/rdf/example"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
    
    <zahtev_za_pristup_informacijama about="http://www.ftn.uns.ac.rs/rdf/examples/zahtev/1" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
        <podaci_o_organu>
            <naziv datatype="xs:string" property="pred:naziv_ustanove">FTN</naziv>
            <sediste property="pred:sediste_ustanove" datatype="xs:string">Novi Sad</sediste>
        </podaci_o_organu>
        <sadrzaj>
            <zahtevi>
                <zahtev id="s_1" otkaceno="false" zahtev="обавештење да ли поседује тражену информацију"/>;
                <zahtev id="s_2" otkaceno="false" zahtev="увид у документ који садржи тражену информацију"/>;
                <zahtev id="s_3" otkaceno="false" zahtev="копију документа који садржи тражену информацију"/>;
                <zahtev id="s_4" otkaceno="false" zahtev="достављање копије документа који садржи тражену информацију">
                    <nacini_dostave>
                        <nacin id="ps_1" nacin="поштом" otkaceno="false"/>
                        <nacin id="ps_2" nacin="електронском поштом" otkaceno="false"/>
                        <nacin id="ps_3" nacin="факсом" otkaceno="false"/>
                        <nacin id="ps_4" nacin="на други начин:" otkaceno="false">
                            <drugi_nacin/>
                        </nacin>
                    </nacini_dostave>
                </zahtev>
            </zahtevi>
            <opis_trazene_informacije property="pred:opis_informacije" datatype="xs:string">Informacija</opis_trazene_informacije>
        </sadrzaj>
        <podnozje>
            <mesto_i_datum>
                <mesto>Novi Sad</mesto>
                <datum_zahteva datatype="xs:string" property="pred:datum_zahteva">2020-12-04</datum_zahteva>
            </mesto_i_datum>
            <informacije_o_traziocu>
                <korisnik_email datatype="xs:string" property="pred:korisnik">vladimirvukovic98@maildrop.cc</korisnik_email>
                <ime_i_prezime datatype="xs:string" property="pred:ime_trazioca">Vladimir Vukovic</ime_i_prezime>
                <adresa>
                    <ulica datatype="xs:string" property="pred:ulica_trazioca">Jevrejska</ulica>
                    <broj datatype="xs:integer" property="pred:broj_kuce_trazioca">10</broj>
                    <mesto property="pred:mesto_trazioca" datatype="xs:string">Novi Sad</mesto>
                </adresa>
                <kontakt datatype="xs:string" property="pred:kontakt_trazioca">21748896</kontakt>
                <potpis/>
            </informacije_o_traziocu>
        </podnozje>
    </zahtev_za_pristup_informacijama>
    
    <zahtev_za_pristup_informacijama about="http://www.ftn.uns.ac.rs/rdf/examples/zahtev/2" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
        <podaci_o_organu>
            <naziv datatype="xs:string" property="pred:naziv_ustanove">FTN</naziv>
            <sediste property="pred:sediste_ustanove" datatype="xs:string">Novi Sad</sediste>
        </podaci_o_organu>
        <sadrzaj>
            <zahtevi>
                <zahtev id="s_1" otkaceno="false" zahtev="обавештење да ли поседује тражену информацију"/>;
                <zahtev id="s_2" otkaceno="false" zahtev="увид у документ који садржи тражену информацију"/>;
                <zahtev id="s_3" otkaceno="false" zahtev="копију документа који садржи тражену информацију"/>;
                <zahtev id="s_4" otkaceno="false" zahtev="достављање копије документа који садржи тражену информацију">
                    <nacini_dostave>
                        <nacin id="ps_1" nacin="поштом" otkaceno="false"/>
                        <nacin id="ps_2" nacin="електронском поштом" otkaceno="false"/>
                        <nacin id="ps_3" nacin="факсом" otkaceno="false"/>
                        <nacin id="ps_4" nacin="на други начин:" otkaceno="false">
                            <drugi_nacin/>
                        </nacin>
                    </nacini_dostave>
                </zahtev>
            </zahtevi>
            <opis_trazene_informacije property="pred:opis_informacije" datatype="xs:string">Informacija</opis_trazene_informacije>
        </sadrzaj>
        <podnozje>
            <mesto_i_datum>
                <mesto>Novi Sad</mesto>
                <datum_zahteva datatype="xs:string" property="pred:datum_zahteva">2020-12-04</datum_zahteva>
            </mesto_i_datum>
            <informacije_o_traziocu>
                <korisnik_email datatype="xs:string" property="pred:korisnik">vladimirvukovic98@maildrop.cc</korisnik_email>
                <ime_i_prezime datatype="xs:string" property="pred:ime_trazioca">Vladimir Vukovic</ime_i_prezime>
                <adresa>
                    <ulica datatype="xs:string" property="pred:ulica_trazioca">Jevrejska</ulica>
                    <broj datatype="xs:integer" property="pred:broj_kuce_trazioca">10</broj>
                    <mesto property="pred:mesto_trazioca" datatype="xs:string">Novi Sad</mesto>
                </adresa>
                <kontakt datatype="xs:string" property="pred:kontakt_trazioca">21748896</kontakt>
                <potpis/>
            </informacije_o_traziocu>
        </podnozje>
    </zahtev_za_pristup_informacijama>
    
    <zahtev_za_pristup_informacijama about="http://www.ftn.uns.ac.rs/rdf/examples/zahtev/3" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
        <podaci_o_organu>
            <naziv datatype="xs:string" property="pred:naziv_ustanove">FTN</naziv>
            <sediste property="pred:sediste_ustanove" datatype="xs:string">Novi Sad</sediste>
        </podaci_o_organu>
        <sadrzaj>
            <zahtevi>
                <zahtev id="s_1" otkaceno="false" zahtev="обавештење да ли поседује тражену информацију"/>;
                <zahtev id="s_2" otkaceno="false" zahtev="увид у документ који садржи тражену информацију"/>;
                <zahtev id="s_3" otkaceno="false" zahtev="копију документа који садржи тражену информацију"/>;
                <zahtev id="s_4" otkaceno="false" zahtev="достављање копије документа који садржи тражену информацију">
                    <nacini_dostave>
                        <nacin id="ps_1" nacin="поштом" otkaceno="false"/>
                        <nacin id="ps_2" nacin="електронском поштом" otkaceno="false"/>
                        <nacin id="ps_3" nacin="факсом" otkaceno="false"/>
                        <nacin id="ps_4" nacin="на други начин:" otkaceno="false">
                            <drugi_nacin/>
                        </nacin>
                    </nacini_dostave>
                </zahtev>
            </zahtevi>
            <opis_trazene_informacije property="pred:opis_informacije" datatype="xs:string">Informacija</opis_trazene_informacije>
        </sadrzaj>
        <podnozje>
            <mesto_i_datum>
                <mesto>Novi Sad</mesto>
                <datum_zahteva datatype="xs:string" property="pred:datum_zahteva">2020-12-04</datum_zahteva>
            </mesto_i_datum>
            <informacije_o_traziocu>
                <korisnik_email datatype="xs:string" property="pred:korisnik">vladimirvukovic98@maildrop.cc</korisnik_email>
                <ime_i_prezime datatype="xs:string" property="pred:ime_trazioca">Vladimir Vukovic</ime_i_prezime>
                <adresa>
                    <ulica datatype="xs:string" property="pred:ulica_trazioca">Jevrejska</ulica>
                    <broj datatype="xs:integer" property="pred:broj_kuce_trazioca">10</broj>
                    <mesto property="pred:mesto_trazioca" datatype="xs:string">Novi Sad</mesto>
                </adresa>
                <kontakt datatype="xs:string" property="pred:kontakt_trazioca">21748896</kontakt>
                <potpis/>
            </informacije_o_traziocu>
        </podnozje>
    </zahtev_za_pristup_informacijama>
    
</lista_zahteva_za_pristup_informacijama>
