=== vukovic98/xml_veb_servisi/apps/poverenik_be/bin/data/resenje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://ftn.uns.ac.rs/resenje"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:resenje="http://ftn.uns.ac.rs/resenje">
  <xs:element name="lista_resenja">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="resenje:resenje"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="resenje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resenje:osnovni_podaci"/>
        <xs:element ref="resenje:sadrzaj"/>
        <xs:element ref="resenje:poverenik"/>
        <xs:element ref="resenje:broj_zalbe"/>
        <xs:element ref="resenje:ishod"/>
      </xs:sequence>
      <xs:attribute name="about" use="required" type="xs:anyURI"/>
      <xs:attribute name="broj" use="required"/>
      <xs:attribute name="vocab" use="required" type="xs:anyURI"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="osnovni_podaci">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resenje:naslov"/>
        <xs:element ref="resenje:datum"/>
        <xs:element ref="resenje:korisnik_email"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naslov">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="datum">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:date">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="korisnik_email">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sadrzaj">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resenje:uvod"/>
        <xs:element ref="resenje:doneto_resenje"/>
        <xs:element ref="resenje:obrazlozenje"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="uvod">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resenje:organ"/>
        <xs:element ref="resenje:podnosilac"/>
        <xs:element ref="resenje:ustanova"/>
        <xs:element ref="resenje:datum_zahteva"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="organ">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="podnosilac">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ustanova">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resenje:naziv"/>
        <xs:element ref="resenje:ulica"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naziv">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="ulica" type="xs:string"/>
  <xs:element name="datum_zahteva">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:date">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="doneto_resenje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resenje:trazeni_dokument"/>
        <xs:element ref="resenje:tekst_resenja"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="trazeni_dokument">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tekst_resenja" type="xs:string"/>
  <xs:element name="obrazlozenje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resenje:tekst_obrazlozenja"/>
        <xs:element ref="resenje:sud"/>
        <xs:element ref="resenje:taksa"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tekst_obrazlozenja" type="xs:string"/>
  <xs:element name="sud" type="xs:string"/>
  <xs:element name="taksa">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:decimal">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="poverenik">
    <xs:complexType mixed="true">
      <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="broj_zalbe">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="ishod">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="datatype" use="required" type="xs:NMTOKEN"/>
          <xs:attribute name="property" use="required" type="xs:NMTOKEN"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vukovic98/xml_veb_servisi/apps/poverenik_be/bin/data/resenje.xml
<?xml version="1.0" encoding="UTF-8"?>
<lista_resenja
    xmlns="http://ftn.uns.ac.rs/resenje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ftn.uns.ac.rs/resenje resenje.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema#"
    xmlns:obav="http://www.ftn.uns.ac.rs/rdf/example"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
    
    <resenje about="http://www.ftn.uns.ac.rs/rdf/examples/resenje/1" broj="071-01-1114/2020-03" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
        <osnovni_podaci>
            <naslov datatype="xs:string" property="pred:naslov">Решење када је жалба основана</naslov>
            <datum datatype="xs:date" property="pred:datum_resenja">2020-06-09</datum>
            <korisnik_email datatype="xs:string" property="pred:korisnik">vladimirvukovic98@maildrop.cc</korisnik_email>
        </osnovni_podaci>
        <sadrzaj>
            <uvod>
                <organ datatype="xs:string" property="pred:organ">Повереник за информације од јавног значаја и заштиту података о личности</organ>
                <podnosilac datatype="xs:string" property="pred:podnosilac">Vladimir Vukovic</podnosilac>
                <ustanova>
                    <naziv datatype="xs:string" property="pred:naziv_ustanove">FTN</naziv>
                    <ulica>Немањина бб</ulica>
                </ustanova>
                <datum_zahteva datatype="xs:date" property="pred:datum_zahteva">2020-04-16</datum_zahteva>
            </uvod>
            <doneto_resenje>
                <trazeni_dokument datatype="xs:string" property="pred:trazeni_dokument">Уговор о раду који је као последњи потписан између тог Факултета и ББ</trazeni_dokument>
                <tekst_resenja>Resio sam da ...</tekst_resenja>
            </doneto_resenje>
            <obrazlozenje>
                <tekst_obrazlozenja>Zbog toga sto ...</tekst_obrazlozenja>
                <sud>Управном суду у Београду</sud>
                <taksa datatype="xs:double" property="pred:taksa">390.00</taksa>
            </obrazlozenje>
        </sadrzaj>
        <poverenik datatype="xs:string" property="pred:poverenik">Милан Мариновић</poverenik>
        <broj_zalbe datatype="xs:string" property="pred:broj_zalbe">1</broj_zalbe>
        <ishod datatype="xs:string" property="pred:ishod">ODOBREN</ishod>
    </resenje>
    
    <resenje about="http://www.ftn.uns.ac.rs/rdf/examples/resenje/2" broj="071-01-1114/2020-03" vocab="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">
        <osnovni_podaci>
            <naslov datatype="xs:string" property="pred:naslov">Решење када је жалба основана</naslov>
            <datum datatype="xs:date" property="pred:datum_resenja">2020-06-09</datum>
            <korisnik_email datatype="xs:string" property="pred:korisnik">vladimirvukovic98@maildrop.cc</korisnik_email>
        </osnovni_podaci>
        <sadrzaj>
            <uvod>
                <organ datatype="xs:string" property="pred:organ">Повереник за информације од јавног значаја и заштиту података о личности</organ>
                <podnosilac datatype="xs:string" property="pred:podnosilac">Vladimir Vukovic</podnosilac>
                <ustanova>
                    <naziv datatype="xs:string" property="pred:naziv_ustanove">FTN</naziv>
                    <ulica>Немањина бб</ulica>
                </ustanova>
                <datum_zahteva datatype="xs:date" property="pred:datum_zahteva">2020-04-16</datum_zahteva>
            </uvod>
            <doneto_resenje>
                <trazeni_dokument datatype="xs:string" property="pred:trazeni_dokument">Уговор о раду који је као последњи потписан између тог Факултета и ББ</trazeni_dokument>
                <tekst_resenja>Resio sam da ...</tekst_resenja>
            </doneto_resenje>
            <obrazlozenje>
                <tekst_obrazlozenja>Zbog toga sto ...</tekst_obrazlozenja>
                <sud>Управном суду у Београду</sud>
                <taksa datatype="xs:double" property="pred:taksa">390.00</taksa>
            </obrazlozenje>
        </sadrzaj>
        <poverenik datatype="xs:string" property="pred:poverenik">Милан Мариновић</poverenik>
        <broj_zalbe datatype="xs:string" property="pred:broj_zalbe">2</broj_zalbe>
        <ishod datatype="xs:string" property="pred:ishod">ODBIJEN</ishod>
    </resenje>
</lista_resenja>
