=== vukovic98/xml_veb_servisi/sluzbenik_be/bin/data/zalba_cutanje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://ftn.uns.ac.rs/zalba_cutanje" xmlns="http://ftn.uns.ac.rs/zalba_cutanje"
  xmlns:zc="http://ftn.uns.ac.rs/zalba_cutanje">
  <xs:element name="zalba_cutanje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zaglavlje"/>
        <xs:element ref="sadrzaj"/>
        <xs:element ref="podnozje"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="zaglavlje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="naslov"/>
        <xs:element ref="primalac_zalbe"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naslov" type="xs:string"/>
  <xs:element name="primalac_zalbe">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="naziv_primaoca"/>
        <xs:element ref="adresa_za_postu"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naziv_primaoca" type="xs:string"/>
  <xs:element name="adresa_za_postu" type="xs:string"/>
  <xs:element name="sadrzaj">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="paragraf"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="paragraf">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="datum"/>
        <xs:element ref="napomena"/>
        <xs:element ref="naziv_organa"/>
        <xs:element ref="razlog_zalbe"/>
        <xs:element ref="zakon"/>
      </xs:choice>
      <xs:attribute name="id" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="napomena" type="xs:string"/>
  <xs:element name="naziv_organa" type="xs:string"> </xs:element>
  <xs:element name="razlog_zalbe" >
    <xs:complexType>
      <xs:choice maxOccurs="1" minOccurs="0">
        <xs:element name="nije_postupio">
          <xs:complexType/>
        </xs:element>
        <xs:element name="nije_postupio_u_celosti">
          <xs:complexType/>
        </xs:element>
        <xs:element name="nije_postupio_u_roku">
          <xs:complexType/>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="zakon">
    <xs:complexType>
      <xs:attribute name="clan" type="xs:integer"/>
      <xs:attribute name="naziv" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="podnozje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="podnosilac_zalbe"/>
        <xs:element ref="datum_i_mesto_zalbe"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="podnosilac_zalbe">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ime_i_prezime"/>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="adresa_podnosioca"/>
          <xs:element ref="drugi_podaci_za_kontakt"/>
          <xs:element ref="potpis"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="ime_i_prezime" type="xs:string"> </xs:element>
  <xs:element name="adresa_podnosioca" type="xs:string"> </xs:element>
  <xs:element name="drugi_podaci_za_kontakt" type="xs:string"> </xs:element>
  <xs:element name="potpis">
    <xs:complexType/>
  </xs:element>
  <xs:element name="datum_i_mesto_zalbe">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="datum"/>
        <xs:element ref="mesto"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="mesto" type="xs:string"> </xs:element>
  <xs:element name="datum" type="xs:date"> </xs:element>
</xs:schema>

=== vukovic98/xml_veb_servisi/sluzbenik_be/bin/data/zalba_cutanje.xml
<?xml version="1.0" encoding="UTF-8"?>
<zalba_cutanje xmlns="http://ftn.uns.ac.rs/zalba_cutanje"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ftn.uns.ac.rs/obavestenje zalba_cutanje.xsd">
    <zaglavlje>
        <naslov>
            ЖАЛБА КАДА ОРГАН ВЛАСТИ НИЈЕ ПОСТУПИО/ није поступио у целости/ ПО ЗАХТЕВУ ТРАЖИОЦА У ЗАКОНСКОМ  РОКУ  (ЋУТАЊЕ УПРАВЕ)
        </naslov>
        <primalac_zalbe>
            <naziv_primaoca>            
                Повереникy за информације од јавног значаја и заштиту података о личности
            </naziv_primaoca>
            <adresa_za_postu>
                Београд, Булевар краља Александрa бр. 15
            </adresa_za_postu>
        </primalac_zalbe>
    </zaglavlje>
    <sadrzaj>
        <paragraf id="p1">
            У складу са <zakon naziv="Закона о слободном приступу информацијама од јавног значаја" clan="22"></zakon> подносим:
            Ж А Л Б У
            против
            <naziv_organa></naziv_organa>
            због тога што орган власти:
            <razlog_zalbe></razlog_zalbe>
            по мом захтеву  за слободан приступ информацијама од јавног значаја који сам поднео  том органу  дана <datum>2020-12-01</datum> године, а којим сам тражио/ла да ми се у складу са <zakon naziv="Законом о слободном приступу информацијама од јавног значаја"></zakon> омогући увид- копија документа који садржи информације  о /у вези са :
        </paragraf>
        <paragraf id="p2">
              На основу изнетог, предлажем да Повереник уважи моју жалбу и омогући ми приступ траженој/им  информацији/ма.
            Као доказ , уз жалбу достављам копију захтева са доказом о предаји органу власти.
            <napomena> Код жалбе  због непоступању по захтеву у целости, треба приложити и добијени одговор органа власти.</napomena>
        </paragraf>
        
    </sadrzaj>
    <podnozje>
        <podnosilac_zalbe>
            <ime_i_prezime>
                
            </ime_i_prezime>
            <potpis></potpis>
            <adresa_podnosioca>
                
            </adresa_podnosioca>
            <drugi_podaci_za_kontakt>
                
            </drugi_podaci_za_kontakt>
            <potpis></potpis>
        </podnosilac_zalbe>
        <datum_i_mesto_zalbe>
            У <mesto>Novom Sadu</mesto>, дана <datum>2020-12-04</datum>
        </datum_i_mesto_zalbe>
    </podnozje>
</zalba_cutanje>
